version: 0.1

environment_variables:
  plaintext:
    SNS_TOPIC_ARN: arn:aws:lambda:us-east-1:019453824943:function:my-react-app

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD          
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - 'aws sns publish --topic-arn arn:aws:lambda:us-east-1:019453824943:function:my-react-app --message "{\"buildId\": \"$CODEBUILD_BUILD_ID\"}"'